#!/bin/bash
#abuild wrover --ip m5-core2.local $*
#abuild wrover -DS3KM1110_DEBUG_COMMANDS -DS3KM1110_DEBUG_DATA -Dvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv $*
abuild wrover --ip rover.local -DS3KM1110_DEBUG_COMMANDS $*




